# -*- coding: utf-8 -*-
"""Analisis_Portafolios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHRI3VCCTIOc3M4eLd18hLDRVqrlBv_n
"""

#!pip install streamlit pandas numpy yfinance matplotlib

#Importación las librerías

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import warnings
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet

warnings.filterwarnings('ignore')

st.markdown("<h1 style='text-align: center; color:#004aad;'>Smart Portafolio - Simulación de Escenarios</h1>", unsafe_allow_html=True)

# Agrega esto justo después de tus imports
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
    
    .main-header {
        font-family: 'Inter', sans-serif;
        text-align: center;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 2rem;
        border-radius: 15px;
        margin-bottom: 2rem;
        color: white;
        box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    }
    
    .main-title {
        font-size: 2.8rem;
        font-weight: 700;
        margin-bottom: 0.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 15px;
    }
    
    .main-subtitle {
        font-size: 1.2rem;
        opacity: 0.9;
        font-weight: 400;
    }
</style>

<div class="main-header">
    <div class="main-title">
        <span></span>
        <span>Smart Portafolio</span>
        <span>📈</span>
    </div>
    <div class="main-subtitle">
        Simulación de Escenarios
    </div>
</div>
""", unsafe_allow_html=True)

st.write("""
Esta aplicación realiza una **simulación de escenarios de inversión**, aplicando la *Teoría Moderna de Portafolios de Markowitz*.

Se analizan tres tipos de portafolios según el perfil de riesgo del inversionista:

- 🟩 **Conservador:** prioriza la estabilidad, minimizando el riesgo.  
- 🟨 **Moderado:** busca equilibrio entre riesgo y rentabilidad.  
- 🟥 **Agresivo:** asume un riesgo alto para intentar maximizar las ganancias.

Los datos se obtienen directamente desde **Yahoo Finance**, permitiendo analizar empresas reales del mercado financiero.
""")

# Configuración de entradas

st.sidebar.markdown("## ⚙️ Configuración del Análisis")

# Entrada libre de tickers
tickers_input = st.sidebar.text_input(
    "Empresas (separa por comas):",
    value="AAPL, MSFT, TSLA"
)

# Convertir texto en lista
tickers = [t.strip().upper() for t in tickers_input.split(",") if t.strip() != ""]

# Rango de fechas
fecha_inicio = st.sidebar.date_input("📅 Fecha Inicial", pd.to_datetime("2020-01-01"))
fecha_fin = st.sidebar.date_input("📅 Fecha Final", pd.to_datetime("2023-12-31"))

# Inversión inicial
inversion_inicial = st.sidebar.number_input("💰 Inversión Inicial (USD)", min_value=1000, value=10000, step=500)

# Frecuencia temporal
frecuencia = st.sidebar.selectbox("⏱️ Frecuencia Temporal", ["Diaria", "Semanal", "Mensual"])

# Botón para ejecutar
descargar = st.sidebar.button("📥 Descargar y Analizar")

# Validación de tickers
def validar_tickers(tickers):
    tickers_validos = []
    for ticker in tickers:
        try:
            info = yf.Ticker(ticker).info
            if info.get('regularMarketPrice') is not None:
                tickers_validos.append(ticker)
            else:
                st.warning(f"⚠️ Ticker {ticker} no encontrado en Yahoo Finance")
        except:
            st.warning(f"⚠️ Error al validar ticker {ticker}")
    return tickers_validos

# Ejecutar análisis al hacer clic
if descargar:
    if len(tickers) == 0:
        st.error("❌ Por favor ingresa al menos un ticker válido")
        st.stop()
    
    tickers = validar_tickers(tickers)
    
    if len(tickers) == 0:
        st.error("❌ No se encontraron tickers válidos")
        st.stop()

    # Descargar datos
    with st.spinner('📥 Descargando datos...'):
        data = yf.download(tickers, start=fecha_inicio, end=fecha_fin)["Close"]
    
    # Mostrar datos
    st.subheader("📊 Datos Descargados")
    st.dataframe(data.tail())

    # Ajustar frecuencia
    if frecuencia == "Semanal":
        data = data.resample('W').last()
    elif frecuencia == "Mensual":
        data = data.resample('M').last()

    # Input de pesos personalizados
    st.sidebar.markdown("### 🎯 Configuración de Pesos")
    opcion_pesos = st.sidebar.radio(
        "Método de asignación:",
        ["Escenario Predefinido", "Pesos Personalizados"]
    )

    if opcion_pesos == "Escenario Predefinido":
        escenario = st.sidebar.selectbox("💰 Escenario de Inversión", ["Conservador", "Moderado", "Agresivo"])
        escenarios = {
            "Conservador": np.linspace(0.6, 0.1, len(tickers)),
            "Moderado": np.linspace(0.4, 0.2, len(tickers)),
            "Agresivo": np.linspace(0.2, 0.6, len(tickers))
        }
        weights = escenarios[escenario]
        weights = weights / np.sum(weights)
    else:
        st.sidebar.markdown("### 🔢 Asigna Pesos Manualmente")
        pesos_manuales = []
        total = 0
        for i, ticker in enumerate(tickers):
            peso = st.sidebar.slider(f"Peso para {ticker}", 0.0, 1.0, 1.0/len(tickers), 0.01)
            pesos_manuales.append(peso)
            total += peso
        
        if abs(total - 1.0) > 0.01:
            st.sidebar.warning(f"⚠️ La suma de pesos es {total:.2f}. Normalizando...")
            weights = np.array(pesos_manuales) / total
        else:
            weights = np.array(pesos_manuales)
        
        escenario = "Personalizado"

    # Cálculos del portafolio
    returns = data.pct_change().dropna()
    mean_returns = returns.mean() * 252
    cov_matrix = returns.cov() * 252

    port_return = np.dot(weights, mean_returns)
    port_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe_ratio = port_return / port_volatility

    returns["Portfolio"] = (returns[tickers] * weights).sum(axis=1)
    valor_portafolio = (1 + returns["Portfolio"]).cumprod() * inversion_inicial

    # Métricas en columnas
    st.subheader("🎯 Resumen Ejecutivo")
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Rendimiento Esperado", f"{port_return:.2%}")
    with col2:
        st.metric("Volatilidad Anual", f"{port_volatility:.2%}")
    with col3:
        st.metric("Ratio de Sharpe", f"{sharpe_ratio:.2f}")
    with col4:
        st.metric("Escenario", escenario)

    # Visualización de Precios
    st.subheader("📈 Evolución de Precios")
    fig1, ax1 = plt.subplots(figsize=(10, 4))
    for ticker in tickers:
        ax1.plot(data.index, data[ticker], label=ticker)
    ax1.set_title("Evolución de Precios Ajustados")
    ax1.set_xlabel("Fecha")
    ax1.set_ylabel("Precio (USD)")
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    st.pyplot(fig1)

    # Evolución del valor monetario
    st.subheader("💵 Evolución del Valor del Portafolio")
    fig2, ax2 = plt.subplots(figsize=(10, 4))
    ax2.plot(valor_portafolio.index, valor_portafolio.values, color='green', linewidth=2)
    ax2.set_title("Evolución del valor monetario del portafolio")
    ax2.set_xlabel("Fecha")
    ax2.set_ylabel("Valor (USD)")
    ax2.grid(True, alpha=0.3)
    ax2.fill_between(valor_portafolio.index, valor_portafolio.values, alpha=0.3, color='green')
    st.pyplot(fig2)

    # Diagrama riesgo - retorno
    st.subheader("📊 Diagrama Riesgo - Retorno")
    asset_returns = mean_returns[tickers]
    asset_risk = returns[tickers].std() * np.sqrt(252)

    fig3, ax3 = plt.subplots(figsize=(8, 6))
    scatter = ax3.scatter(asset_risk.values, asset_returns.values, c='blue', s=100, alpha=0.7)
    for i, ticker in enumerate(tickers):
        ax3.text(asset_risk.values[i] + 0.002, asset_returns.values[i], ticker, fontsize=9, ha='left', va='center')
    
    # Agregar punto del portafolio completo
    ax3.scatter(port_volatility, port_return, c='red', s=150, marker='*', label='Portafolio')
    ax3.text(port_volatility + 0.002, port_return, 'Tu Portafolio', fontsize=10, ha='left', va='center', color='red')
    
    ax3.set_xlabel("Volatilidad (Riesgo)")
    ax3.set_ylabel("Rendimiento Esperado")
    ax3.set_title("Diagrama Riesgo - Retorno")
    ax3.legend()
    ax3.grid(True, linestyle='--', alpha=0.6)
    st.pyplot(fig3)

    # Heatmap de correlaciones
    st.subheader("🔥 Heatmap de Correlaciones")
    corr_matrix = returns[tickers].corr()
    
    fig4, ax4 = plt.subplots(figsize=(8, 6))
    im = ax4.imshow(corr_matrix, cmap="coolwarm", interpolation="nearest", vmin=-1, vmax=1)
    
    # Mostrar valores en las celdas
    for i in range(len(corr_matrix)):
        for j in range(len(corr_matrix)):
            text = ax4.text(j, i, f'{corr_matrix.iloc[i, j]:.2f}',
                           ha="center", va="center", color="black", fontsize=10)
    
    plt.colorbar(im, ax=ax4)
    ax4.set_xticks(range(len(corr_matrix)))
    ax4.set_xticklabels(corr_matrix.columns, rotation=45)
    ax4.set_yticks(range(len(corr_matrix)))
    ax4.set_yticklabels(corr_matrix.columns)
    ax4.set_title("Matriz de Correlaciones")
    st.pyplot(fig4)

    # Visualización del portafolio
    st.subheader("🥧 Distribución del Portafolio")
    fig5, ax5 = plt.subplots(figsize=(8, 6))
    wedges, texts, autotexts = ax5.pie(weights, labels=tickers, autopct='%1.1f%%', startangle=90)
    ax5.set_title(f"Distribución del Portafolio ({escenario})")
    # Mejorar legibilidad
    for autotext in autotexts:
        autotext.set_color('white')
        autotext.set_fontweight('bold')
    st.pyplot(fig5)

    # Interpretación del escenario
    st.markdown("---")
    st.subheader("🧠 Interpretación del Escenario Seleccionado")
    if escenario == "Conservador":
        st.info("🟩 Este portafolio busca minimizar el riesgo, con un enfoque en estabilidad. Su rendimiento esperado es menor, pero ofrece menor volatilidad y pérdidas potenciales.")
    elif escenario == "Moderado":
        st.info("🟨 Este portafolio equilibra riesgo y rendimiento. Es ideal para inversores con tolerancia media al riesgo que buscan un crecimiento sostenido.")
    elif escenario == "Agresivo":
        st.info("🟥 Este portafolio asume mayor riesgo con el objetivo de maximizar el rendimiento. Es adecuado para inversionistas con alta tolerancia a la volatilidad y posibles pérdidas.")
    else:
        st.info("📊 Portafolio personalizado con pesos definidos manualmente. Revise las métricas para evaluar el balance riesgo-rendimiento.")

    # Solo mostrar comparación de escenarios si no es personalizado
    if escenario != "Personalizado":
        # Comparación de escenarios
        st.subheader("📊 Comparación de Escenarios de Inversión")
        fig_all, axs = plt.subplots(1, 3, figsize=(15, 5))
        for i, (nombre, base_pesos) in enumerate({
            "Conservador": np.linspace(0.6, 0.1, len(tickers)),
            "Moderado": np.linspace(0.4, 0.2, len(tickers)),
            "Agresivo": np.linspace(0.2, 0.6, len(tickers))
        }.items()):
            w = base_pesos / np.sum(base_pesos)
            labels = tickers[:len(w)]
            axs[i].pie(w, labels=labels, autopct='%1.1f%%', startangle=90)
            axs[i].set_title(nombre, fontweight='bold')
        plt.suptitle("Distribución de Pesos por Tipo de Portafolio", fontsize=14, fontweight='bold')
        plt.tight_layout()
        st.pyplot(fig_all)

        # Evaluación y recomendación de escenarios
        st.subheader("🤖 Recomendación de Escenario Óptimo")
        resultados = {}
        for nombre, pesos in {
            "Conservador": np.linspace(0.6, 0.1, len(tickers)),
            "Moderado": np.linspace(0.4, 0.2, len(tickers)),
            "Agresivo": np.linspace(0.2, 0.6, len(tickers))
        }.items():
            w = pesos / np.sum(pesos)
            rendimiento = np.dot(w, mean_returns)
            riesgo = np.sqrt(np.dot(w.T, np.dot(cov_matrix, w)))
            sharpe = rendimiento / riesgo
            resultados[nombre] = {"rendimiento": rendimiento, "riesgo": riesgo, "sharpe": sharpe}

        df_resultados = pd.DataFrame(resultados).T
        df_resultados = df_resultados.sort_values("sharpe", ascending=False)

        # Mostrar tabla con estilo
        st.dataframe(df_resultados.style.format({
            "rendimiento": "{:.2%}",
            "riesgo": "{:.2%}",
            "sharpe": "{:.2f}"
        }).highlight_max(subset=['sharpe'], color='lightgreen'))

        mejor_escenario = df_resultados.index[0]
        st.success(f"✅ El escenario más eficiente según el Ratio de Sharpe es: **{mejor_escenario}** 🎯")

        if mejor_escenario == "Conservador":
            st.info("💡 Recomendación: Este portafolio ofrece mayor estabilidad y menor riesgo. Ideal para perfiles que priorizan seguridad sobre rentabilidad.")
        elif mejor_escenario == "Moderado":
            st.info("💡 Recomendación: Este portafolio equilibra riesgo y rendimiento, siendo adecuado para inversores con tolerancia media al riesgo.")
        else:
            st.info("💡 Recomendación: Este portafolio maximiza el rendimiento a costa de mayor volatilidad. Ideal para perfiles arriesgados que buscan crecimiento a largo plazo.")

    # Descarga de resultados
    st.subheader("📥 Descarga de Resultados")

    # Exportar datos a Excel
    excel_buffer = BytesIO()
    with pd.ExcelWriter(excel_buffer, engine='xlsxwriter') as writer:
        data.to_excel(writer, sheet_name='Precios')
        returns.to_excel(writer, sheet_name='Rendimientos')
        if escenario != "Personalizado":
            df_resultados.to_excel(writer, sheet_name='Escenarios')

    st.download_button(
        label="📊 Descargar en Excel",
        data=excel_buffer.getvalue(),
        file_name="analisis_portafolio.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

    # Generar reporte PDF
    st.subheader("📄 Generar Reporte en PDF")
    pdf_buffer = BytesIO()

    # Crear documento
    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Título
    title = Paragraph("<b><font size=18 color='#004aad'>SMART PORTAFOLIO - REPORTE DE INVERSIÓN</font></b>", styles["Title"])
    elements.append(title)
    elements.append(Spacer(1, 0.2 * inch))

    # Datos generales
    intro = Paragraph(f"""
    <font size=12>
    <b>Escenario seleccionado:</b> {escenario}<br/>
    <b>Activos analizados:</b> {', '.join(tickers)}<br/>
    <b>Inversión inicial:</b> ${inversion_inicial:,.2f}<br/>
    <b>Periodo de análisis:</b> {fecha_inicio} a {fecha_fin}
    </font>
    """, styles["Normal"])
    elements.append(intro)
    elements.append(Spacer(1, 0.2 * inch))

    # Resultados
    resumen_data = [
        ["Métrica", "Valor"],
        ["Rendimiento esperado", f"{port_return:.2%}"],
        ["Volatilidad esperada", f"{port_volatility:.2%}"],
        ["Ratio de Sharpe", f"{sharpe_ratio:.2f}"],
    ]
    
    if escenario != "Personalizado":
        resumen_data.append(["Escenario recomendado", mejor_escenario])

    table = Table(resumen_data, hAlign='LEFT')
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.3 * inch))

    # Distribución de pesos
    pesos_data = [["Activo", "Peso"]]
    for ticker, peso in zip(tickers, weights):
        pesos_data.append([ticker, f"{peso:.1%}"])
    
    pesos_table = Table(pesos_data, hAlign='LEFT')
    pesos_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgreen),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    elements.append(Paragraph("<b>Distribución del Portafolio</b>", styles["Normal"]))
    elements.append(pesos_table)
    elements.append(Spacer(1, 0.3 * inch))

    # Conclusión
    if escenario != "Personalizado":
        conclusion = Paragraph(f"""
        <font size=12>
        La simulación de escenarios permite observar cómo el riesgo y el rendimiento están estrechamente relacionados.<br/>
        El portafolio <b>{mejor_escenario}</b> presenta la mejor eficiencia según el Ratio de Sharpe.<br/><br/>
        <b>Interpretación:</b><br/>
        {("Este portafolio prioriza la estabilidad, ideal para perfiles conservadores." if mejor_escenario == "Conservador" 
        else "Este portafolio equilibra riesgo y rendimiento, ideal para inversores moderados." 
        if mejor_escenario == "Moderado" 
        else "Este portafolio busca maximizar ganancias, ideal para perfiles arriesgados.")}
        </font>
        """, styles["Normal"])
    else:
        conclusion = Paragraph(f"""
        <font size=12>
        Portafolio personalizado con distribución específica según preferencias del usuario.<br/>
        <b>Rendimiento esperado:</b> {port_return:.2%}<br/>
        <b>Volatilidad esperada:</b> {port_volatility:.2%}<br/>
        <b>Eficiencia (Sharpe):</b> {sharpe_ratio:.2f}<br/>
        </font>
        """, styles["Normal"])
    
    elements.append(conclusion)

    # Guardar PDF
    doc.build(elements)
    pdf_buffer.seek(0)

    st.download_button(
        label="📑 Descargar Reporte en PDF",
        data=pdf_buffer,
        file_name="Reporte_Portafolio.pdf",
        mime="application/pdf"
    )

else:
    st.info("👈 Configura los parámetros en la barra lateral y haz clic en 'Descargar y Analizar' para comenzar el análisis.")
